---
- name: Quick-fix alvistack.podman role by adding dbus-user-session
  # This fix seems to be not the best, as it pulls roughly 20 MiB additional
  # dependencies. https://github.com/alvistack/ansible-role-podman/issues/17#issuecomment-1352787379
  apt:
    name: dbus-user-session
    state: present
    update_cache: true
    cache_valid_time: 3600
