---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - libpq-dev
      - postfix
      - postgresql-15
      - postgresql-15-ip4r
      - python3-virtualenv
      - uwsgi
      - uwsgi-plugin-python3
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Copy postfix config
  ansible.builtin.template:
    dest: /etc/postfix/main.cf
    src: postfix_main.cf.j2
    mode: "0640"
    owner: root
    group: root
  notify: Restart postfix

- name: Copy uwsgi app config
  ansible.builtin.template:
    dest: /etc/uwsgi/apps-enabled/ff-wizard.ini
    src: uwsgi-ff-wizard.ini.j2
    mode: "0640"
    owner: root
    group: root
  notify: Restart uwsgi

- name: Create directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: www-data
    group: www-data
    mode: "0750"
  with_items:
    - /var/www/nipap-wizard/
    - /var/log/nipap-wizard/

- name: Checkout ff-wizard
  become: true
  become_user: www-data
  ansible.builtin.git:
    repo: https://github.com/freifunk-berlin/config.berlin.freifunk.net.git
    version: main
    dest: /var/www/nipap-wizard
    force: true
  notify: Restart uwsgi

- name: Copy ff-wizard config
  ansible.builtin.template:
    dest: /var/www/nipap-wizard/config.cfg
    src: wizard-config.cfg.j2
    mode: "0640"
    owner: www-data
    group: www-data
  notify: Restart uwsgi

- name: Install nipap in venv
  ansible.builtin.pip:
    requirements: /var/www/nipap-wizard/requirements.txt
    virtualenv: /var/www/nipap-wizard/env
    virtualenv_command: virtualenv --python=python3.11
    virtualenv_python: python3.11
  notify: Restart uwsgi

- name: Set owner of nipap dir
  ansible.builtin.file:
    state: directory
    path: /var/www/nipap-wizard/
    owner: www-data
    group: www-data
    recurse: true
