---
# This playbook deploys the whole application stack in this site.

- name: Apply common configuration
  hosts: all
  become: true
  vars_files:
    - inventory/group_vars/users
  roles:
    - common
    - ryandaniels.create_users
  tags: basic_provision

- name: Set up buildbot environment
  hosts: buildbot
  become: true
  roles:
    - buildbot
    - geerlingguy.nginx
    - systemli.letsencrypt

- name: Set up buildbot workers
  hosts: buildbotworker
  become: true
  roles:
    - alvistack.podman
    - podman_fix
    - buildbot_worker

- name: Set up config server
  hosts: configserver
  vars_files:
    - inventory/group_vars/configserver
  become: true
  roles:
    - nipap
    - caddy
    - ff_wizard
