---
# This playbook deploys the whole application stack in this site.

- name: Deploy users to all servers
  hosts: all
  become: true
  vars_files:
    - inventory/group_vars/users
  roles:
    - ryandaniels.create_users
  tags: user_provision

- name: Apply common configuration and packages
  hosts: all,!users_only,!proxmox
  become: true
  roles:
    - common
  tags: basics

- name: Set up buildbot environment
  hosts: buildbot
  become: true
  roles:
    - buildbot
    - caddy

- name: Set up buildbot workers
  hosts: buildbotworker
  become: true
  roles:
    - buildbot_worker

- name: Set up config server
  hosts: configserver
  vars_files:
    - inventory/group_vars/configserver
  become: true
  roles:
    - nipap
    - caddy
    - ff_wizard

- name: Set up monitoring server
  hosts: monitoring
  become: true
  roles:
    - caddy
    - ff_monitor

- name: Set up tunneldigger
  hosts: tunneldigger
  become: true
  roles:
    - tunneldigger
  tags:
    - tunneldigger

- name: Set up website
  hosts: website
  become: true
  roles:
    - caddy

- name: Set up proxmox hosts
  hosts: proxmox
  become: true
  roles:
    - proxmox
  tags:
    - proxmox

- name: Set up wiki
  hosts: wiki
  become: true
  roles:
    - caddy
    - php
    - mariadb
    - ff_wiki
  tags:
    - wiki

- name: Set up hopglass
  hosts: utils
  become: true
  roles:
    - caddy
    - php
    - ff_util
  tags:
    - utils
