---
# This playbook deploys the whole application stack in this site.

- name: Deploy users to all servers
  hosts: all
  become: true
  vars_files:
    - inventory/group_vars/users
  roles:
    - ryandaniels.create_users
  tags: user_provision

- name: Apply common configuration and packages
  hosts: all,!users_only
  become: true
  roles:
    - common
  tags: basics

- name: Set up buildbot environment
  hosts: buildbot
  become: true
  roles:
    - buildbot
    - geerlingguy.nginx
    - systemli.letsencrypt

- name: Set up buildbot workers
  hosts: buildbotworker
  become: true
  roles:
    - buildbot_worker

- name: Set up config server
  hosts: configserver
  vars_files:
    - inventory/group_vars/configserver
  become: true
  roles:
    - nipap
    - caddy
    - ff_wizard

- name: Set up monitoring server
  hosts: monitoring
  become: true
  roles:
    - caddy
    - ff_monitor

- name: Set up tunneldigger
  hosts: tunneldigger,!b.tunnel.berlin.freifunk.net
  become: true
  roles:
    - tunneldigger
  tags:
    - tunneldigger

- name: Set up website
  hosts: website
  become: true
  roles:
    - caddy

- name: Set up hypervisor
  hosts: hypervisor
  become: true
  roles:
    - hypervisor
