---
# This playbook deploys the whole application stack in this site.

- name: Apply common configuration
  hosts: all,!vpn03d.berlin.freifunk.net,!vpn03f.berlin.freifunk.net
  become: true
  vars_files:
    - inventory/group_vars/users
  roles:
    - common
    - ryandaniels.create_users
  tags: basic_provision


- name: Deploy Users to VPN03 Ubuntu servers
  hosts:
    - vpn03d.berlin.freifunk.net
    - vpn03f.berlin.freifunk.net
  become: true
  vars_files:
    - inventory/group_vars/users
  roles:
    - ryandaniels.create_users

- name: Set up buildbot environment
  hosts: buildbot
  become: true
  roles:
    - buildbot
    - geerlingguy.nginx
    - systemli.letsencrypt

- name: Set up buildbot workers
  hosts: buildbotworker
  become: true
  roles:
    - alvistack.podman
    - podman_fix
    - buildbot_worker

- name: Set up config server
  hosts: configserver
  vars_files:
    - inventory/group_vars/configserver
  become: true
  roles:
    - nipap
    - caddy
    - ff_wizard

- name: Set up monitoring server
  hosts: monitor.berlin.freifunk.net
  become: true
  roles:
    - caddy
