---
# This playbook deploys the whole application stack in this site.

- name: Apply common configuration
  hosts: all,!c.tunnel.berlin.freifunk.net,!d.tunnel.berlin.freifunk.net
  become: true
  vars_files:
    - inventory/group_vars/users
  roles:
    - common
    - ryandaniels.create_users
  tags: basic_provision

- name: Deploy Users to tunneldigger Ubuntu servers
  hosts:
    - c.tunnel.berlin.freifunk.net
    - d.tunnel.berlin.freifunk.net
  become: true
  vars_files:
    - inventory/group_vars/users
  roles:
    - ryandaniels.create_users
  tags: basic_provision

- name: Set up buildbot environment
  hosts: buildbot
  become: true
  roles:
    - buildbot
    - geerlingguy.nginx
    - systemli.letsencrypt

- name: Set up buildbot workers
  # buildbot has docker already. Don't deploy podman for now.
  hosts: buildbotworker, !buildbot.berlin.freifunk.net
  become: true
  roles:
    - alvistack.podman
    - podman_fix
    - buildbot_worker

- name: Set up config server
  hosts: configserver
  vars_files:
    - inventory/group_vars/configserver
  become: true
  roles:
    - nipap
    - caddy
    - ff_wizard

- name: Set up monitoring server
  hosts: monitoring
  become: true
  roles:
    - caddy

- name: Set up monitoring server
  hosts: monitoring_new
  become: true
  roles:
    - ff_monitor
