---
# ansible dependencies
# usage: ansible-galaxy install --force --role-file requirements.yml
roles:
  - src: ryandaniels.create_users
    version: 2.0.1
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.mysql
    version: 4.0.1
  - name: community.general
    version: 12.3.0
