---
# ansible dependencies
# usage: ansible-galaxy install -r requirements.yml
roles:
  - src: ryandaniels.create_users
    version: 1.0.8
  - src: geerlingguy.nginx
    version: 3.1.0
  - src: geerlingguy.docker
    version: 4.1.3
  - src: systemli.letsencrypt
    version: 2.1.0
  - src: alvistack.podman
    version: 6.3.1
