---
# ansible dependencies
# usage: ansible-galaxy install -r requirements.yml
roles:
  - src: ryandaniels.create_users
    version: 2.0.0
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.mysql
    version: 3.15.0
  - name: community.general
    version: 11.2.1