---
roles:
  - src: ryandaniels.create_users
    version: 1.0.7
  - src: geerlingguy.nginx
    version: 3.1.0
  - src: geerlingguy.docker
    version: 4.1.3
  - src: systemli.letsencrypt
    version: 2.1.0
