---
# tasks to be run on all machines
- name: Install packages
  ansible.builtin.apt:
    name: "{{ hypervisor_packages }}"
    state: present
    update_cache: true


# - name: Copy custom motd
#   ansible.builtin.template:
#     src: motd.j2
#     dest: /etc/motd
#     mode: "0640"
#     owner: root
#     group: root

# Todo
# - bridges
# sysctl
# custom boot options
# add users to group
# add 8021q to /etc/modules
# host specific stuff (hp, disable intel_iommu // /etc/modprobe.d/blacklist-hp.conf )
# hugepages (worth the effort?)
#  Modprobe  br_netfilter and: 
# /etc/sysctl.d/bridge.conf
# net.bridge.bridge-nf-call-ip6tables=0
# net.bridge.bridge-nf-call-iptables=0
# net.bridge.bridge-nf-call-arptables=0
# 
# or 
# /etc/udev/rules.d/99-bridge.rules
# ACTION=="add", SUBSYSTEM=="module", KERNEL=="br_netfilter", RUN+="/sbin/sysctl -p /etc/sysctl.d/bridge.conf"
# 
