---
# tasks to be run on all machines
- name: Install packages
  ansible.builtin.apt:
    name: "{{ hypervisor_packages }}"
    state: present
    update_cache: true

- name: Copy custom modprobe
  ansible.builtin.template:
    src: "{{ hypervisor_modprobe }}"
    dest: /etc/modprobe.d/freifunk
    mode: "0640"
    owner: root
    group: root

- name: Copy custom sysctl
  ansible.builtin.template:
    src: "{{ hypervisor_sysctl }}"
    dest: /etc/sysctl.d/freifunk
    mode: "0640"
    owner: root
    group: root

# Todo
# - bridges
# custom boot options
# add users to group
