---
# tasks to be run on all machines
- name: Install packages
  ansible.builtin.apt:
    name: "{{ hypervisor_packages }}"
    state: present
    update_cache: true

- name: Copy custom modprobe
  ansible.builtin.template:
    src: "{{ hypervisor_modprobe }}"
    dest: /etc/modprobe.d/freifunk
    mode: "0640"
    owner: root
    group: root

- name: Copy custom sysctl
  ansible.builtin.template:
    src: "{{ hypervisor_sysctl }}"
    dest: /etc/sysctl.d/freifunk
    mode: "0640"
    owner: root
    group: root

- name: Copy libvirt-guests defaults
  ansible.builtin.template:
    src: libvirt-guests-default.j2
    dest: /etc/default/libvirt-guests
    mode: "0640"
    owner: root
    group: root

- name: Define bridges
  ansible.builtin.template:
    src: "bridge.j2"
    dest: "/etc/network/interfaces.d/{{ item.name }}"
    mode: "0644"
    owner: root
    group: root
  loop: "{{ hypervisor_networks }}"
  when: hypervisor_networks is defined

- name: Define libvirt networks
  community.libvirt.virt_net:
    command: define
    name: "{{ item.name }}"
    xml: '{{ lookup("template", "libvirt-network.xml.j2") }}'
  loop: "{{ hypervisor_networks }}"
  when: hypervisor_networks is defined

- name: Set libvirt Networks active and autostart
  community.libvirt.virt_net:
    name: "{{ item.name }}"
    autostart: true
    state: active
  loop: "{{ hypervisor_networks }}"
  when: hypervisor_networks is defined
