---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - bridge-utils
      - dnsmasq
      - gcc
      - git
      - iproute2
      - iptables
      - libevent-dev
      - libnetfilter-conntrack-dev
      - libnfnetlink-dev
      - nftables
      - python3-dev
      - python3-pip
      - python3-venv
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Set nftables conf
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    mode: "0644"
    owner: root
    group: root
  notify: Restart nftables

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Checkout tunneldigger
  ansible.builtin.git:
    repo: https://github.com/wlanslovenija/tunneldigger.git
    version: c50ef46d78d797750979ebf2f8ddc5aa993a02ae
    dest: "{{ tunneldigger_path }}"
    force: true
  notify: Restart tunneldigger

- name: Create tunneldigger venv
  ansible.builtin.command: /usr/bin/python3 -m venv {{ tunneldigger_path }}/env
  args:
    creates: "{{ tunneldigger_path }}/env"
  notify: Restart tunneldigger

- name: Install tunneldigger in venv
  ansible.builtin.shell:
  args:
    cmd: source {{ tunneldigger_path }}/env/bin/activate && cd {{ tunneldigger_path }}/broker && pip install --upgrade setuptools && python setup.py install
    creates: "{{ tunneldigger_path }}/broker/dist/"
    executable: /bin/bash

- name: Copy tunneldigger service file
  ansible.builtin.template:
    src: tunneldigger.service.j2
    dest: /etc/systemd/system/tunneldigger.service
    mode: "0644"
    owner: root
    group: root
  notify: Restart tunneldigger

- name: Copy tunneldigger configuration file
  ansible.builtin.template:
    src: l2tp_broker.cfg.j2
    dest: "{{ tunneldigger_path }}/broker/l2tp_broker.cfg"
    mode: "0644"
    owner: root
    group: root
  notify: Restart tunneldigger

- name: Copy tunneldigger scripts
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0755"
    owner: root
    group: root
  notify: Restart tunneldigger
  loop:
    - {src: ff.session.mtu-changed.sh.j2, dest: "{{ tunneldigger_path }}/broker/scripts/ff.session.mtu-changed.sh"}
    - {src: ff.session.up.sh.j2, dest: "{{ tunneldigger_path }}/broker/scripts/ff.session.up.sh"}
    - {src: dhcp-script.sh.j2, dest: "{{ tunneldigger_path }}/broker/scripts/dhcp-script.sh"}

- name: Make sure the correct Kernel modules will load on boot
  ansible.builtin.template:
    src: modules-tunneldigger.conf.j2
    dest: /etc/modules-load.d/tunneldigger.conf
    mode: "0644"
    owner: root
    group: root
  notify: Restart tunneldigger

- name: Copy dnsmasq config
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    mode: "0644"
    owner: root
    group: root
  notify: Restart dnsmasq

- name: Allow ipv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true

- name: Copy prometheus node_exporter script for tunneldigger
  ansible.builtin.template:
    src: tunneldigger_exporter.sh.j2
    dest: /opt/tunneldigger_exporter.sh
    mode: "0750"
    owner: root
    group: root

- name: Run Prometheus Exporter every minute
  ansible.builtin.cron:
    name: Prometheus tunneldigger exporter
    minute: "*"
    job: /opt/tunneldigger_exporter.sh
    user: root

- name: Set conntrack size
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/conntrack.conf
    line: options nf_conntrack hashsize=32768
    owner: root
    group: root
    mode: "0644"
    create: true
