---
- name: Install dependencies
  apt:
    name:
      - bridge-utils
      - dnsmasq
      - git
      - iproute2
      - libevent-dev
      - nftables
      - python-dev
      - python3-venv
      - python3-pip
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Checkout tunneldigger
  git:
    repo: 'https://github.com/wlanslovenija/tunneldigger.git'
    version: master
    dest: "{{ tunneldigger_path }}"
    force: true
  notify: Restart tunneldigger

- name: create tunneldigger venv
  shell: "python3 -m venv {{ tunneldigger_path }}/env"
  args:
    creates: "{{ tunneldigger_path }}/env"
  notify: Restart tunneldigger

- name: install tunneldigger in venv
  shell: "source {{ tunneldigger_path }}/env/bin/activate && cd {{ tunneldigger_path }}/broker && python setup.py install"
  args:
    creates: "{{ tunneldigger_path }}/broker/dist/"
    executable: /bin/bash

- name: Copy tunneldigger service file
  template:
    src: "tunneldigger.service.j2"
    dest: /etc/systemd/system/tunneldigger.service
    mode: 0644
    owner: root
    group: root
  notify: Restart tunneldigger

- name: Copy tunneldigger configuration file
  template:
    src: "l2tp_broker.cfg.j2"
    dest: "{{ tunneldigger_path }}/broker/l2tp_broker.cfg"
    mode: 0644
    owner: root
    group: root
  notify: Restart tunneldigger

- name: "Copy tunneldigger scripts: setup_interface.sh"
  template:
    src: "setup_interface.sh.j2"
    dest: "{{ tunneldigger_path }}/broker/scripts/setup_interface.sh"
    mode: 0755
    owner: root
    group: root
  notify: Restart tunneldigger

- name: "Copy tunneldigger scripts: functions.sh"
  template:
    src: "functions.sh.j2"
    dest: "{{ tunneldigger_path }}/broker/scripts/functions.sh"
    mode: 0755
    owner: root
    group: root
  notify: Restart tunneldigger

- name: "Make sure the correct Kernel modules will load on boot"
  template:
    src: modules-tunneldigger.conf.j2
    dest: /etc/modules-load.d/tunneldigger.conf
    mode: 0644
    owner: root
    group: root
  notify: Restart tunneldigger

- name: "Copy dnsmasq config"
  template:
    src: "dnsmasq.conf.j2"
    dest: /etc/dnsmasq.conf
    mode: 0644
    owner: root
    group: root
  notify: Restart dnsmasq
