---
- name: Restart tunneldigger
  systemd:
    daemon_reload: true
    name: tunneldigger
    enabled: true
    state: restarted

- name: Restart dnsmasq
  systemd:
    daemon_reload: true
    name: dnsmasq
    enabled: true
    state: restarted

- name: Load nftables rules
  command: "/usr/sbin/nft -f /etc/nftables.conf"
