---
- name: Restart tunneldigger
  ansible.builtin.systemd:
    daemon_reload: true
    name: tunneldigger
    enabled: true
    state: restarted

- name: Restart dnsmasq
  ansible.builtin.systemd:
    daemon_reload: true
    name: dnsmasq
    enabled: true
    state: restarted


- name: Restart nftables
  ansible.builtin.systemd:
    daemon_reload: true
    name: nftables
    enabled: true
    state: restarted
