---
- name: Install restic
  ansible.builtin.apt:
    name:
      - restic
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Add systemd service
  ansible.builtin.template:
    src: restic-backup.service.j2
    dest: /etc/systemd/system/restic-backup.service
    mode: "0644"
  notify: Reload systemd

- name: Add systemd timer for restic
  ansible.builtin.template:
    src: restic-backup.timer.j2
    dest: /etc/systemd/system/restic-backup.timer
    mode: "0644"
  notify: Reload systemd

- name: Enable and start restic timer
  ansible.builtin.systemd:
    name: restic-backup.timer
    enabled: true
    state: started
  when: ansible_check_mode == false
