---
- name: Restart rrdcached
  ansible.builtin.systemd:
    daemon_reload: true
    name: rrdcached
    enabled: true
    state: restarted

- name: Restart collectd
  ansible.builtin.systemd:
    daemon_reload: true
    name: collectd
    enabled: true
    state: restarted

- name: Restart php-fpm
  ansible.builtin.systemd:
    daemon_reload: true
    name: php8.2-fpm
    enabled: true
    state: restarted

- name: Restart prometheus
  ansible.builtin.systemd:
    daemon_reload: true
    name: prometheus
    enabled: true
    state: restarted

- name: Restart grafana
  ansible.builtin.systemd:
    daemon_reload: true
    name: grafana-server
    enabled: true
    state: restarted
