- name: Restart rrdcached
  systemd:
    daemon_reload: true
    name: rrdcached
    enabled: true
    state: restarted

- name: Restart collectd
  systemd:
    daemon_reload: true
    name: collectd
    enabled: true
    state: restarted

- name: Restart php-fpm
  systemd:
    daemon_reload: true
    name: php7.4-fpm
    enabled: true
    state: restarted

- name: Restart prometheus
  systemd:
    daemon_reload: true
    name: prometheus
    enabled: true
    state: restarted
