---
# This extends the default yaml-lint conf by adjusting some options.

extends: default

# ignore possible venv directory and encrypted ansible vault files in the buildbot and worker directories
ignore: |
  venv
  inventory/host_vars/buildbot.berlin.freifunk.net/main.yml
  inventory/host_vars/buildbot-worker-*/main.yml

rules:
  comments:
    level: error
  comments-indentation:
    level: error
  document-start:
    level: error
  line-length:
    max: 2048
    level: warning
