---

- name: Create directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: www-data
    group: www-data
    mode: "0770"
  with_items:
    - /srv/www/berlin.freifunk.net
    - /srv/www/dev.berlin.freifunk.net
