- name: uwsgi | restart
  systemd:
    daemon_reload: true
    name: uwsgi
    enabled: true
    state: restarted

- name: postfix | restart
  systemd:
    daemon_reload: true
    name: uwsgi
    enabled: true
    state: restarted
