---
- name: Restart uwsgi
  ansible.builtin.systemd:
    daemon_reload: true
    name: uwsgi
    enabled: true
    state: restarted

- name: Restart postfix
  ansible.builtin.systemd:
    daemon_reload: true
    name: uwsgi
    enabled: true
    state: restarted
