---
- name: Restart uwsgi
  systemd:
    daemon_reload: true
    name: uwsgi
    enabled: true
    state: restarted

- name: Restart postfix
  systemd:
    daemon_reload: true
    name: uwsgi
    enabled: true
    state: restarted
