---
hypervisor_packages:
  - libvirt-daemon-system
  - vlan
  - bridge-utils
  - ethtool
  - python3-lxml
  - python3-libvirt
hypervisor_modprobe: modprobe.j2
hypervisor_sysctl: sysctl.j2

hypervisor_networks:
  - name: AS44194
    bridge_interface: ens2f1np1.123
    address: 77.87.50.2/24
    gateway: 77.87.50.1
  - name: Strom
    bridge_interface: ens2f1np1.1312
  - name: in-berlin
    bridge_interface: ens2f1np1.1300
