---
- name: install labgrid-dependencies
  apt:
    name:
      - python3
      - python3-virtualenv
      - python3-pip
      - python3-setuptools
      - virtualenv
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: clone labgrid-repo
  git:
    repo: https://github.com/labgrid-project/labgrid
    dest: /opt/labgrid/

- name: install labgrid in a virtual env
  pip:
    requirements: /opt/labgrid/requirements.txt
    virtualenv: /opt/labgrid_venv/
  register: venv_created

- name: did we install already?

- name: run setup.py, if it wasn't run before
  command: cd /opt/labgrid/ && python3 setup.py install # this should be run within the venv!

- name: clone falter-tests to labrig-deployment
  git:
    repo: https://github.com/labgrid-project/labgrid # TODO: add right repo
    dest: /opt/labgrid_falter_tests
...