---
- name: Configure prometheus-node-exporter
  ansible.builtin.template:
    src: prometheus-node-exporter.j2
    dest: /etc/default/prometheus-node-exporter
    mode: "0640"
    owner: root
    group: root
  notify: Restart prometheus-node-exporter
  