---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart rest-server
  ansible.builtin.systemd:
    name: restic-rest-server
    enabled: true
    state: restarted
